input {
  beats {
    port => 5044
    host => "0.0.0.0"
  }
}

filter {
  if [type] == "suricata" {
    json {
      source  => "message"
      target  => "suricata"
    }
    date {
      match  => ["[suricata][timestamp]", "ISO8601"]
      target => "@timestamp"
    }
    mutate {
      add_field => { "[@metadata][index]" => "suricata-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "suricata-%{+YYYY.MM.dd}"
  }
}
